Repository testit-tms/adapters-js, pull requests merged in 2023-04, with the labels that each got.

#17 Feature/add should create work item property
  .gitignore
  testit-adapter-codecept/package.json
  testit-adapter-codecept/src/services/runs.builder.ts
  testit-adapter-cucumber/package.json
  testit-adapter-cucumber/src/storage.ts
  testit-adapter-jest/package.json
  testit-adapter-jest/src/testitEnvironment.ts
Labels: documentation, enhancement

#19 Fixed adapter-jest package build.
  testit-adapter-jest/package.json
Labels: bug

#16 add workflow
  .github/release-drafter.yml
  .github/workflows/code_checks.yml
  .github/workflows/label-verifier.yml
  .github/workflows/publish.yml
  .github/workflows/release-draft.yml
  testit-adapter-codecept/package-lock.json
  testit-adapter-cucumber/package-lock.json
  testit-adapter-jest/package-lock.json
Labels: enhancement
