Repository testit-tms/adapters-js, pull requests merged in 2025-09, with the labels that each got.

#105 fix: update playwright attachment parsing
  testcafe-reporter-testit/package.json
  testit-adapter-codecept/package.json
  testit-adapter-cucumber/package.json
  testit-adapter-jest/package.json
  testit-adapter-mocha/package.json
  testit-adapter-playwright/package.json
  testit-adapter-playwright/src/labels.ts
  testit-adapter-playwright/src/models/result.ts
  testit-adapter-playwright/src/reporter.ts
  testit-adapter-playwright/src/utils.ts
  testit-js-commons/package.json
  testit-js-commons/src/common/utils/utils.ts
  testit-js-commons/src/strategy/strategy.factory.ts
Labels: enhancement

#106 chore: attachment parsing
  testit-adapter-playwright/src/utils.ts
Labels: enhancement

#108 feat: support api-client 6.3.1.
  README.md
  testcafe-reporter-testit/package.json
  testit-adapter-codecept/package.json
  testit-adapter-cucumber/package.json
  testit-adapter-jest/package.json
  testit-adapter-mocha/package.json
  testit-adapter-playwright/package.json
  testit-js-commons/package.json
Labels: documentation, enhancement

#110 Fix/tms 35396
  testcafe-reporter-testit/package.json
  testit-adapter-codecept/package.json
  testit-adapter-cucumber/package.json
  testit-adapter-cucumber/src/utils.ts
  testit-adapter-jest/package.json
  testit-adapter-mocha/package.json
  testit-adapter-playwright/package.json
  testit-adapter-playwright/src/reporter.ts
  testit-js-commons/package.json
  testit-js-commons/src/services/autotests/autotests.converter.ts
Labels: bug
