Repository testit-tms/adapters-js, pull requests merged in 2025-07, with the labels that each got.

#95 fix: TMS-33524 fix html tags escaping
  .gitignore
  testcafe-reporter-testit/package.json
  testit-adapter-codecept/package.json
  testit-adapter-cucumber/package.json
  testit-adapter-jest/package.json
  testit-adapter-mocha/package.json
  testit-adapter-playwright/package.json
  testit-js-commons/jest.config.js
  testit-js-commons/package.json
  testit-js-commons/src/common/utils/html-escape.util.test.ts
  testit-js-commons/src/common/utils/html-escape.util.ts
  testit-js-commons/src/common/utils/index.ts
  testit-js-commons/src/services/autotests/autotests.service.ts
  testit-js-commons/src/services/testruns/testruns.service.ts
  testit-js-commons/tsconfig.json
Labels: bug

#96 feat: update the package versions.
  README.md
  testcafe-reporter-testit/package.json
  testit-adapter-codecept/package.json
  testit-adapter-cucumber/package.json
  testit-adapter-jest/package.json
  testit-adapter-mocha/package.json
  testit-adapter-playwright/package.json
  testit-js-commons/package.json
Labels: documentation

#97 Feat/update versions
  testcafe-reporter-testit/package.json
  testit-adapter-codecept/package.json
  testit-adapter-cucumber/package.json
  testit-adapter-jest/package.json
  testit-adapter-mocha/package.json
  testit-adapter-playwright/package.json
  testit-js-commons/package.json
Labels: documentation

#98 feat: support tms 5.4.
  README.md
  testcafe-reporter-testit/package.json
  testit-adapter-codecept/package.json
  testit-adapter-cucumber/package.json
  testit-adapter-jest/package.json
  testit-adapter-mocha/package.json
  testit-adapter-playwright/package.json
  testit-js-commons/package.json
Labels: documentation, enhancement

#100 feat: fix ci tests
  .github/workflows/code_checks.yml
  .github/workflows/test.yml
  testit-adapter-codecept/src/builders/result.builder.ts
Labels: enhancement, tests
